### PR TITLE
make python name2 function faster by hardcoding the set of chars with…

### PR DESCRIPTION
**Pull request by jamadagni**
… normative aliases

other minor changes:
_test() now outputs only a sample of blocks

note:
hardcoding should be fine since anyhow the whole library has to be updated when a new Unicode version is released
the _charsForName2() function called by _test() makes hardcoding the list very easy

### CODE REVIEW

**Comment by JoesCat** [comment]
The problem with hard-coded tables are that they need to be maintained, and are easily forgotten. There's several tables in fontforge that are in need of updating and can use automation.
Looking at this, I think it's best to put this in buildnameslist, then it can be used in libuninames as well as your python wrapper. Seeing that libuninameslist basically points at constant strings we'd have to return a stringlength (to K.I.S. and avoid adding alloc and friends).
What do you think of returning NULL or const str ptr plus string length?
const char * names2(unicode, &strlen);

**Comment by jamadagni** [comment]
Hello. In fact I tried looking into the C library and add a name2
function there but the code of buildnameslist was quite hard to read
and understand so I gave up. Somebody with better knowledge of the
original coding might have to look in.

-- 
Shriramana Sharma ஶ்ரீரமணஶர்மா श्रीरमणशर्मा

**Comment by JoesCat** [comment]
Well, you saw a need to create it, and went to the effort to code a solution that worked.
I looked at your code, saw what you created to solve that problem, so call this partial version2:
https://github.com/fontforge/libuninameslist/commits/add_name2_issue11

Sometimes we have to toss-out old code to makes something better, but...
Version2 would not exist if it wasn't for your version1.
Thanks for your code - it helped form version2.

Still need to add the C calling functions, but that's not too far behind.

**Comment by JoesCat** [comment]
Hi @jamadagni,
Can you take a look at the current library and see if you can modify your wrapper to access the available 'new' functions? This should allow a huge speed boost since it's now built into the C library.

**Comment by jamadagni** [comment]
Superseded by https://github.com/fontforge/libuninameslist/pull/13.

**Pull request closed without merging**
