### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by jtanx**
- Add git.mk to ignore files
- Simplify python build - don't bother installing, just make a python wheel. User can pip install the wheel if they want.
- Add travis

### CODE REVIEW

**Comment by JoesCat** [comment]
Great addition with git travis appveyor (It shows Win/Mac are okay with localized variables which was a concern seeing all those warnings appear in Linux).

Would've been nice to include install python by default, but python has proved to be problematic finding a great method that kept C first and python as the extra (with autoconf). I wonder if host==win* use PYTHON otherwise use PYTHON2+PYTHON3 for everything else would've been sufficient.
Not to hot about the additional pip requirements, but otherwise ok with this as is.

If you think of anything else to add, go ahead and merge to master when you're ready, I'll start with unicode 11.0 late next week for July1st.

**Comment by jtanx** [comment]
> Would've been nice to include install python by default, but python has proved to be problematic finding a great method that kept C first and python as the extra (with autoconf). I wonder if host==win* use PYTHON otherwise use PYTHON2+PYTHON3 for everything else would've been sufficient.
Not to hot about the additional pip requirements, but otherwise ok with this as is.

To be honest, adding python into the build system isn't adding much value. Users can easily just run setup.py with the version of their choice, instead of having to configure it as part of the build. 

Also pip is the de-facto package manager, and is installed by default on later versions of python.

**Comment by JoesCat** [comment]
Thanks for the FYI on pip. I looked at setup.py and looked at "import"

> To be honest, adding python into the build system isn't adding much value. Users can easily just run setup.py with the version of their choice, instead of having to configure it as part of the build.

I'm thinking more in terms of distros, that-way it's added when users download from their repository. Some repos are divided into binary installs and dev headers, and not everyone can or will build from source. Adding new features to a library of this size can be considered a rare event, and it seems there is a lot of python users, so this adds another tool that can be used, so it seemed worth trying the effort to auto-install.

Removing config.guess, config.sub may be an issue with Fedora. It was a solution to allow building on aarch64 while still holding onto AC_PREREQ([2.64]) for older setups.

**Comment by jtanx** [comment]
> I'm thinking more in terms of distros, that-way it's added when users download from their repository

I'd say it's moving to be frowned upon to install packages into system python (or at least is a decision that should be made at the discretion of the user) - especially in this case, where the library is pure python, unlike in FontForge's case, which actually generates a cpython binding (actually even in that case, you could generate prebuilt wheels, although I guess with the number of dependencies FontForge has it'd take a bit of effort).

It's fairly common to use virtualenv/conda environments/pipenv to install python packages into, instead of having everything in system python, especially as this approach does not require root permissions. If you really want easy usability of it, maybe try publishing to https://pypi.org/, then users can `pip install libuninameslist`.

> Removing config.guess, config.sub may be an issue with Fedora. It was a solution to allow building on aarch64 while still holding onto AC_PREREQ([2.64]) for older setups.

Do they not use the dist tarballs, which have all that bundled, and the configure script generated already? Unless they need a specific version of those files?

**Comment by JoesCat** [comment]
> I'd say it's moving to be frowned upon to install packages into system python.

Seems logical - will go with your strategy (user installed).

> Do they not use the dist tarballs, which have all that bundled, and the configure script generated already? Unless they need a specific version of those files?

I don't know, but then again, it has also been a few years, and perhaps it's no longer an issue or hurdle. This is something that needs to be asked.

**Comment by JoesCat** [comment]
Hi @nirik, this was brought-up as an issue with libspiro 5 years ago, but also of interest here too: https://sourceforge.net/p/libspiro/bugs/1/
We're looking at removing config.guess and config.sub from autoconf, would this be an issue if configure.ac AC_PREREQ remained at 2.64 ?

Hi @aborrero, are you still involved with MIPS?
If yes, would you know if editing configure.ac from AC_PREREQ([2.64]) to AC_PREREQ([2.69]) would be an issue with builds such as this library plus libspiro?

**Comment by jtanx** [comment]
I just read that bug report. So what that was saying was because at the time, the bundled config.guess/config.sub were too old, so we either had to upgrade the provided files, or they had to rerun autoreconf.

One thing that maybe isn't made clear is that when you autoreconf, config.guess/config.sub are regenerated/copied in by that process, overwriting your existing versions - hence why I want to remove it, every time I run it, it changes the files, so you end up with a modified files git status on them.

When you run `make dist` and generate a distribution tarball, the configure script (not configure.ac), plus config.guess/config.sub are provided as part of it, so you don't have to have autoconf yourself, you just run the configure script as provided. 

So based on that, I'd say it's safe to remove. The workflow then would be from git source, you always just autoreconf, which generates/copies in those files, and from dist releases, just run `./configure` without autoreconf'ing.

**Comment by JoesCat** [comment]
At the time of the bug report, there was no config.guess or config.sub included.
I chose option 3 to add config.guess and config.sub using the latest version available then, which can be pulled-in with wget here:
https://www.gnu.org/software/gettext/manual/html_node/config_002eguess.html

Right now, both files are approx a year+ old (~20170701), so if your process is replacing them, you should be seeing newer files. If they're older files, then it may be a problem (older than 2013? is a long way back), I'm expecting the 5+ year buffer also obsoletes the bug, but then you also have the distros that have 10year support too.

**Comment by jtanx** [comment]
Given that the bug report points to https://sourceforge.net/p/libspiro/bugs/1/ as being upstream, I assume they're referring to https://sourceforge.net/projects/libspiro/files/libspiro/20071029/libspirojava.tar.bz2, which does include config.guess/config.sub/configure.

**Comment by JoesCat** [comment]
looking at the patch, config.guess and config.sub existed, but were very old, from about 2003.
it was an update from 2003 to 2013, autoconf still wasn't part of either library yet.

**Comment by JoesCat** [comment]
Hi @jtanx - safe to merge, or not yet?

**Comment by jtanx** [comment]
@JoesCat  sorry, yep, merged now.

**Comment by jtanx** [comment]
It's not a python3 vs 2 issue, Windows CI at least runs against python2.

Try

```
python2 -m pip install --upgrade wheel
```

and/or

```
python2 -m pip install --upgrade setuptools 
```

**Pull request merged**
