### PR TITLE
pacman failing recently - Get pacman updated

### PR DESCRIPTION
**Pull request by JoesCat**

### CODE REVIEW

**Comment by jtanx** [comment]
These appveyor changes don't make a whole load of sense. The original issue was probably transient anyway (it's related to gpg signing and probably the keyserver being down or something).

**Comment by JoesCat** [comment]
This is pretty-much a dead branch - not for merging.
The original problem was indeed a signature change as one maintainer left and a two maintainers replaced him.

I was looking at separating the tests to see if we could matrix in cygwin and mingw32 code but I'm running out of time to play with this further.

The travis code was interesting too - only the linux branch saw the frenchlib and grabbed it. The other OSes expected to look in installed libraries before linking to them.

At this time - it looks like best direction is a summary of "Reduce number of updates by three. Add more CPUs.", and then closing this PR.

 I was trying-out the different CPUs listed in Travis, appears

**Comment by JoesCat** [comment]
Seems the x390 build was happy with seeing -luninameslist-fr in this order:
make
make install
make check
The arm build was okay with 'make check' after the 'make install', but didn't like the plain 'make' with the added french library.

After install, it's not an issue...but during building and checking looks like this could use some work, or maybe exclude the tests for those platforms.

**Comment by jtanx** [comment]
> The original problem was indeed a signature change as one maintainer left and a two maintainers replaced him.

I don't know where you're getting that idea from, maybe confusing msys with msys2?

**Comment by JoesCat** [comment]
> confusing msys with msys2?

Probably yes.
...however - it was interesting to see what happened on the arm and s390x without having to dig through other (static) distro logs.
Closing PR

**Pull request closed without merging**
