### PR TITLE
add python wrapper

### PR DESCRIPTION
**Pull request by jamadagni**

### CODE REVIEW

**Comment by JoesCat** [comment]
Thanks @jamadagni,
This looks interesting - I'll have a closer look at this Wednesday night.
Questions of interest are:
- how to distribute this? for example, as an extra file, or an install? (affects Makefile.am)
- how to test this? (makes it easier to be accepted as valid for various platforms, example list here: https://packages.debian.org/sid/libuninameslist-dev ).

Thanks,
Joe

**Comment by jamadagni** [comment]
Hello. It goes into the /usr/lib/pythonX.Y/dist-packages/ folders for both Py 2 and 3. Running it as a standalone script executes the simple tests.

**Comment by JoesCat** [comment]
Good info,
I'll look into finding some examples of Makefile.am to do that, if you have something ready (or URL), that's great.

**Comment by JoesCat** [comment]
I was reading-up on wrappers and came to reading "find_libraries"
https://docs.python.org/3/library/ctypes.html#finding-shared-libraries

then I came back and looked at CDLL("libuninameslist.so.1") in your code, which is sort-of hard coded to finding version 1, and probably limited further only to linux due to ".so".
At the moment, I've got a few libuninameslist.so ranging from 2013 upto the current 1, next year I expect it gets upgraded again and then another version bump up.

I did not check this out, but what do you think of using find_library(uninameslist)

**Comment by JoesCat** [comment]
Thanks @jamadagni,
Readme.md is probably going to need something mentioned so users are aware of your new file.

I'm currently reading through a couple different [AM_PATH_PYTHON](https://www.gnu.org/software/automake/manual/html_node/Python.html) is a bit too heavy-handed for usage here since this is still a C library (with minimal dependencies) with an extra python script, instead of a python program with a C-helper (AM_PATH_PYTHON throws in dependencies and no clear method of doing --with/without).
...reading further, seems autotools and python setup.py are different beasts...

**Comment by JoesCat** [comment]
updated a bit further so it can be installed...

**Pull request merged**
